### ISSUE TITLE
Toolbar - Page may not be loaded when extraction request sent

### ISSUE THREAD

**Issue by michaelsframe** [Sotera/DatawakeDepot#105]
Currently we send the HTML body to the extractor after the page loads but not necessarily before the page finishes being rendered.  This can cause extraction to not extract all terms in the body.

Add a 1 second delay to the scraper.js before sending the request on to give the page time to finish rendering.

**Comment by michaelsframe** [comment]
completed and added pull request #106

**Comment by bmcdougald** [comment]
I've only seen this happen once, but so far have not been able to repro it on this fix branch.  Assuming this fixed the issue.
