### ISSUE TITLE
Depot: URL Extractions Table, only Value sortable column

### ISSUE THREAD

**Issue by bmcdougald** [Sotera/DatawakeDepot#107]
Value seems to be the only sortable column in this table, clicking on sort for any of the other columns changes nothing.

**Comment by michaelsframe** [comment]
removed st-pipe, set proper sort fields
https://github.com/Sotera/DatawakeDepot/commit/65ba564e43476168e04fed6a77891b765861d930

**Comment by bmcdougald** [comment]
Checked and closing as fixed
