### ISSUE TITLE
Toolbar: Cancel from "create trail" mode kills picklist forcing user to relog

### ISSUE THREAD

**Issue by bmcdougald** [Sotera/DatawakeDepot#118]
If you use the toolbar picklist to create a new trail, then decide not to create a trail and click on cancel...it kills the picklist for trail so it will not accept any selection.  The only way to get the functionality of trail selection back is to logout then back in again.

**Comment by bwhiteman** [comment]
verified, i thought deleting the text would reenable selection but it does not.

**Comment by bmcdougald** [comment]
This was fixed, tested, and merged
