### ISSUE TITLE
Depot: Screens double scrolling when window size shorter than content

### ISSUE THREAD

**Issue by bmcdougald** [Sotera/DatawakeDepot#132]
The form area forms a 2nd scrollbar for the browser when the window right pane content exceeds window height.  When you scroll, it also grabs the branding section of the navbar and scrolls it off the screen as well.  AdminLTE site talks about setting layout to "fixed" in the body tag to solve this in the left sidebar.  I don't know if something similar would solve it for the right panel content, but that may be a good starting place.

![screen shot 2016-01-21 at 9 48 49 am](https://cloud.githubusercontent.com/assets/10615545/12485395/38da13e0-c024-11e5-853d-76d44a98b726.png)

**Comment by bwhiteman** [comment]
This looks like a browser specific issue that may be different based on OS.
- Mac Chrome: the right pane scrolls to the end then the left panel scrolls if you continue to scroll.
- Mac FF: Only the right panel scrolls unless you move your cursor over the left panel, then it scrolls.

**Comment by bmcdougald** [comment]
Could very well be.  I see this on Ubuntu:FF, but checked it on Mac:FF and, like you, I don't see it there.  Need to investigate this further (lower priority) to see if we should add the fixed class or something to ensure consistent performance regardless of OS when using the same browser brand.

**Comment by michaelsframe** [comment]
should be fixed with server side paging #144

**Comment by justinlueders** [comment]
Does this work even if you make the window smaller?

**Comment by bmcdougald** [comment]
Looks like this is working now.  Dunno if it's due to changes Mike made that addressed it, or something else...but closing for now as fixed indirectly.
