### ISSUE TITLE
Toolbar: Need to ditch cookie when logging out

### ISSUE THREAD

**Issue by bmcdougald** [Sotera/DatawakeDepot#133]
Currently, if you log out, the session cookie may still be present.  This allows a user to access depot content even if the previous user has logged out.

**Comment by michaelsframe** [comment]
Can not reproduce. @bmcdougald Are you still seeing this behavior?

**Comment by bmcdougald** [comment]
Looks like logout is truly logging out now.  Closing this ticket for now.  If it comes back we can revisit this.
