### ISSUE TITLE
Depot: Need to add user info to some persisted data

### ISSUE THREAD

**Issue by bmcdougald** [Sotera/DatawakeDepot#137]
We need to add username for certain items persisted to Datawake so that the information can be filtered later.  This becomes a real issue when multiple people share the same trail.  Saving user info and filtering by user enables users to only see stuff they did without data from other users mixed in.

This needs to be present on Trail URLs (who browsed what pages on a given trail), Domain Items (to tell who added them), and possibly extractions (so it only displays extractions relevant to the specified user's trailURLs and Domain Items).

**Comment by michaelsframe** [comment]
Added to TrailUrl, no need to add it to extractions as those are tied to the trailUrl.

Added to DomainItems

**Comment by bmcdougald** [comment]
Looks good...info in both places is being persisted.
