### ISSUE TITLE
Depot: Trails page not respecting admin role

### ISSUE THREAD

**Issue by bmcdougald** [Sotera/DatawakeDepot#138]
If you create a trail under a user, then go to the trails tab while logged in as admin, you can't see the trail created by the user.  The trail shows up in other tables as a badge..for example the Teams tab has a trails column and the admin user can see the trail name badge created by the user.  But the Trails tab table is empty or only shows Trails for the admin.

**Comment by michaelsframe** [comment]
Modified Domain, Trails, and Forensic to check for isAdmin flag and if true, show all records of that type.

**Comment by bmcdougald** [comment]
Looks like I can see user content as admin now.  - closing fixed
