### ISSUE TITLE
Depot: Team Edit form checkboxes do not appear to be saving

### ISSUE THREAD

**Issue by bmcdougald** [Sotera/DatawakeDepot#140]
If you edit a team, the checkboxes for members and domains have selectable values.  If you select the values and Save, the Team table does not reflect the checked items in their columns.  If you open edit for the team again, you may see one of the groups of checkboxes unchecked again and the other still retaining checkmarks (which should have displayed but didn't).

**Comment by michaelsframe** [comment]
should be fixed with #143 
https://github.com/Sotera/DatawakeDepot/commit/ecd0980671786624938dc2f2020d7a3d44a4fe8a

**Comment by bmcdougald** [comment]
This was not completely fixed with #143 

This is very similar to #150 the only difference here, is the table columns weren't updating with the selections in the checkboxes.  That part seems to have been fixed by #143 but checkmarks still are not being retained when you return to the edit window even though it clearly shows selected items for those in the main table.  

Closing this ticket as fixed, and tracking the checkbox behavior specifically in #150
