### ISSUE TITLE
Panel: Changing page before extracting request processed may kill panel on subsequent pages

### ISSUE THREAD

**Issue by bmcdougald** [Sotera/DatawakeDepot#142]
Need to try and root cause this further to see if we can repro it reliably.  If you change pages while the panel is displaying "extracting..." the next page that loads has no panel.  You can toggle the panel with the toolbar button and it still will not show.  Stopping and restarting the trail also did not bring the panel back.  The only way I got it back was to close the browser and restart it.

**Comment by michaelsframe** [comment]
This should be OBE with #161.  Confirm?

**Comment by bmcdougald** [comment]
fixed as panel bug OBE
