### ISSUE TITLE
Depot: Edit domain brings up empty form

### ISSUE THREAD

**Issue by bmcdougald** [Sotera/DatawakeDepot#143]
Even if you retype the values in this form, it will fail to save.  Gives a GREEN error (odd, should be red I'd think) that reports the Domain couldn't be saved [Object, object]

**Comment by michaelsframe** [comment]
fixed edit domain as well as trail url, extractions, entity types
https://github.com/Sotera/DatawakeDepot/commit/ecd0980671786624938dc2f2020d7a3d44a4fe8a

**Comment by bmcdougald** [comment]
Looks like this got fixed with Mike's checkin.
