### ISSUE TITLE
Depot: Domain Items table not sorting on Domains

### ISSUE THREAD

**Issue by bmcdougald** [Sotera/DatawakeDepot#154]
More column sorting problems, not sorting right.   Think it might have something to do with the labels.

Domains column in Domain items
Types column in Forensic/Entities Tab

**Comment by michaelsframe** [comment]
fixed table headers for sorting and pushed to develop

**Comment by michaelsframe** [comment]
This should be working now, confirm?

**Comment by bmcdougald** [comment]
@michaelsframe Neither locations for the ones mentioned are working right.  Domain column in Domain Items.  For Forensic/Entities tab, Types is working right, but the URL column doesn't sort at all yet controls are present in the header.
