### ISSUE TITLE
Word Cloud doesn't render correctly

### ISSUE THREAD

**Issue by bwhiteman** [Sotera/DatawakeDepot#16]
The word cloud renders in a collapsed way when the tab isn't active when clicking the graph button.

**Comment by bwhiteman** [comment]
Merged into ticket 12. There is about a second of latency on the redraw where the cloud is still collapsed before re-rendering.

**Comment by bmcdougald** [comment]
There's about a 2 second delay...I think it's trivial.  Closing as fixed/working/acceptable
