### ISSUE TITLE
Depot: Trail view slow to load after viewing trail object

### ISSUE THREAD

**Issue by michaelsframe** [Sotera/DatawakeDepot#167]
When viewing a trail's JSON we are not clearing the object from memory when the trail list view is reloaded.  This makes things go VERY slow after viewing JSON.

Need to clear this object from memory after use.
While there, would make sense to only load necessary trail fields (trail url, url extractions) for the list view.  Large objects cause the overall page to load slowly.

**Comment by bmcdougald** [comment]
this is working much better...closing as fixed.  Pull request processed.
