### ISSUE TITLE
Multiple pages scraped for each page visit

### ISSUE THREAD

**Issue by bwhiteman** [Sotera/DatawakeDepot#18]
If you visit a page especially with ads, the trail will show multiple pages for this page. Reuters.com is a good example

**Comment by bwhiteman** [comment]
The fix for this isn't perfect, pages like reuters.com still render twice such as:
http://www.reuters.com/ & http://www.reuters.com/#yWbjtMd2JP6gIR6l.97 but it does take care of the ads.

**Comment by bmcdougald** [comment]
seeing multiple hits for the exact same reuters url, but it indeed does take care of the ad content.
