### ISSUE TITLE
Toolbar DW Icon should link back to the website

### ISSUE THREAD

**Issue by bwhiteman** [Sotera/DatawakeDepot#20]
When a user clicks on the datawake icon in the left corner of the plugin, the datawake website should be opened.

**Comment by michaelsframe** [comment]
To clarify behavior, if already logged in the user should be taken to the default dashboard, otherwise they'll be taken to the login page.

**Comment by bmcdougald** [comment]
This is not happening.  Actually it's entering the URL to the base site URL twice.  For example, when you click on the DW Icon it tries to take you to a page like:
http://<serveraddress>:3000http://<serveraddress>:3000
