### ISSUE TITLE
Create a trail from the Toolbar

### ISSUE THREAD

**Issue by bwhiteman** [Sotera/DatawakeDepot#21]
The user should be able to create a trail from the plugin.

**Comment by bwhiteman** [comment]
Whether it be a link to the create trail depot page or a modal, the user needs to be able to create a trail directly from the plugin. User feedback has been that having to go to the depot to create a trail is too time consuming.

**Comment by michaelsframe** [comment]
User should be able to type in a new Trail name.  We don't really have a place to put a description there, so should we default description to match trail name when created from the toolbar?  User can always edit that via the Depot after.

**Comment by bmcdougald** [comment]
User can successfully add a new trail from the toolbar.
