### ISSUE TITLE
Toolbar: Remove team dropdown (assume 1 team per user)

### ISSUE THREAD

**Issue by bwhiteman** [Sotera/DatawakeDepot#22]
Users should only belong to 1 team. Remove team from the plugin and forensic views so that the user only has to select domain and trail.

**Comment by michaelsframe** [comment]
Disagree, users can belong to more than 1 team.  This is how the model is currently developed.

**Comment by bwhiteman** [comment]
To simplify the ux, we will remove team from the plugin and only assign users to a single team and default to using it.

**Comment by michaelsframe** [comment]
Completed in #21
