### ISSUE TITLE
TrailUrls should be filtered by Trail

### ISSUE THREAD

**Issue by bwhiteman** [Sotera/DatawakeDepot#24]
The Trail URL's page should have a drop down with the user's trails. Once a trail is selected, the list should populate with URL's for that trail

**Comment by michaelsframe** [comment]
in light of #13, is this still necessary?

**Comment by bwhiteman** [comment]
I'll check as soon as that branch passes test.

**Comment by bwhiteman** [comment]
The trailUrl's view still shows all trail urls. It needs to either be filtered or removed entirely.

**Comment by michaelsframe** [comment]
I had left the menu item there until Brodie passed pull request #33, in case the revised functionality was broken we had to have a way to get to the TrailUrls.  I'm done with the trail refactor so the menu item can now be removed (I checked in the config removing it yesterday after Brodie completed the pull). 
removed with this commit:
https://github.com/Sotera/DatawakeDepot/commit/33453ea2c639927dfcfbca005658846881af36b3
