### ISSUE TITLE
Page importance ("Page Rank" panel widget)

### ISSUE THREAD

**Issue by bwhiteman** [Sotera/DatawakeDepot#26]
The user should be able to mark a page as either relevant or irrelevant. This could be as simple as a check/x button in the plugin or div the default should be unspecified.

**Comment by bwhiteman** [comment]
This is important to Brian S. Once team has been removed from the plugin, it may be easiest to put it in the bar as simple glyph buttons that mark a page as relevant/irrelevant. The default would be unspecified and no response should be required.

**Comment by michaelsframe** [comment]
This should specifically be implemented as the "Page Rank" panel widget.  I plan to work on this next.

**Comment by bmcdougald** [comment]
pull request completed.
