### ISSUE TITLE
User dashboard

### ISSUE THREAD

**Issue by bwhiteman** [Sotera/DatawakeDepot#28]
A normal user should only have access to Domains, Trails, and forensic.

**Comment by bwhiteman** [comment]
This is to simplify the the front-end for the normal user. The left panel should be collapsed and only the Domains, trail, and forensic should be on the dashboard.

**Comment by bwhiteman** [comment]
The dashboard only has forensic, trails, and domains.
The top left DatawakeDepot icon links back to the dashboard and the left sidebar is collapsed on login.

**Comment by bmcdougald** [comment]
This was verified and merged via pull request issue #35
