### ISSUE TITLE
Stanbol Extractor not returning anything.

### ISSUE THREAD

**Issue by bwhiteman** [Sotera/DatawakeDepot#30]

**Comment by bwhiteman** [comment]
When running with the stanbol extractor, their are time that nothing is returned by the extractor and no error logging in the depot or the extractor.

**Comment by bwhiteman** [comment]
After adding in some logging to the request from the depot, the extractor is returning a 413 error due to the form expanding past the default 100kb in the loopback config.

**Comment by bmcdougald** [comment]
looks to be extracting on larger content now just fine
