### ISSUE TITLE
Add extractor source to extractions

### ISSUE THREAD

**Issue by bwhiteman** [Sotera/DatawakeDepot#32]
For analysis especially if using multiple extractors that do the same task (NER) we need to include an extractor source field to the URL extraction and have all the extractors add their name.

**Comment by bwhiteman** [comment]
Extractor has been added to the forensic entities view, and trailExtractions view as well as the trailExtractions add form.

The Stanbol, Stanford, and Regex extractors have also been updated and the new versions need to be running to see this functionality working.

**Comment by bmcdougald** [comment]
This looks like it's working now.
