### ISSUE TITLE
Depot Scrolling can break

### ISSUE THREAD

**Issue by bmcdougald** [Sotera/DatawakeDepot#34]
I've noticed behavior where if you have "scrolling" set for the depot and view the tab for URLs visited when it has enough content to scroll off the browser window you might see an issue where when you scroll to the bottom, you may not be able to get back to the top.

Not sure what triggers this because it doesn't happen all the time.  I thought it was triggered by starting a trail on another tab then coming back to the depot where you were scrolled to the bottom.  But that can't cause it reliably either.  When the error occurs, a white band for the title of the page (i.e. Forensic) extends through the side bar as well.  when in that state, scrolling is broken.  Suspect this is a bug with the admin template

**Comment by bwhiteman** [comment]
I've been unable to reproduce this.

**Comment by michaelsframe** [comment]
I've seen it happen when we have lots of data (trail Urls specifically).  Functionality changed in #13 should prevent a lot of this.

Ultimately we should have a max page size and page results.   Once we have a ton of Trails, Urls, and Extracted items performance is currently significantly impacted.  I'd mark this as a feature request.

**Comment by michaelsframe** [comment]
should be fixed with #144

**Comment by bmcdougald** [comment]
Think this is solved with the server side paging implementation, as I haven't seen it again during testing this week.  Closing as fixed
