### ISSUE TITLE
URLExtractions list should be filtered by domain, trail, and url

### ISSUE THREAD

**Issue by bwhiteman** [Sotera/DatawakeDepot#41]
The URLExtractions list view needs to be filtered by domain, trail, and URL. Only the current users domains and trails should be available.

The current behavior causes OOM errors and can take a long time to load wile not providing any value to the user. 

As a work around, we could remove this page and use only the entities grid in forensic.

**Comment by michaelsframe** [comment]
A fix to this was checked in with #13 (pull request #39) yesterday.It filters the trail urls and extractions to only the relevant items.

**Comment by bwhiteman** [comment]
@michaelsframe Does this mean only the relevant items are shown in the browser panel? In the depot, it still looks like it shows everything.

**Comment by michaelsframe** [comment]
Currently a user sees all Trails And all Domains (from dashboard 'chip').  Once there, viewing domain items/entity types will only show the relevant items for the domain that linked them there.
Trails work same way, with Urls/Extractions only showing the relevant items for the trail that linked them there.

So sounds like the one part missing is to filter the original Domain and Trail views to only show items for the user's Team?

**Comment by bwhiteman** [comment]
If you get to those pages from the trails or domains page, we need to remove them from the sidebar.

**Comment by michaelsframe** [comment]
Agreed, once the functionality has passed for each Trails and Domains then the menu item will be removed.  Until then it helps having an alternate way to get to them.

**Comment by michaelsframe** [comment]
Completed. Also removed Feeds, domainItems, and Transmissions from menu.
