### ISSUE TITLE
Toolbar Logout button text larger than button

### ISSUE THREAD

**Issue by bwhiteman** [Sotera/DatawakeDepot#49]
<img width="1433" alt="screen shot 2015-12-17 at 9 02 14 am" src="https://cloud.githubusercontent.com/assets/1516655/11871353/00bd127a-a49d-11e5-91b6-4a35c3cbd471.png">
The text on the logout button is larger than the button. The easiest fix is probably to remove the user name.

**Comment by michaelsframe** [comment]
The plugin is going to be reworked (several related issues #20, #45, #48, #49, etc).  We should group all those visualization changes together into one issue, leaving only the new functionality like #21.

These should all be modified to say "Toolbar" versus "Plugin".  The Addin portion is a bit of a different creature.

**Comment by michaelsframe** [comment]
Handled in #21.
