### ISSUE TITLE
Info panel opens inside of ads

### ISSUE THREAD

**Issue by bwhiteman** [Sotera/DatawakeDepot#52]
<img width="1437" alt="screen shot 2015-12-17 at 9 27 35 am" src="https://cloud.githubusercontent.com/assets/1516655/11872012/256a9d32-a4a1-11e5-9c8a-3926e0f577ff.png">
On some sites, the info panel opens inside of an ad instead of in the main page. Cnn.com is an example.

**Comment by michaelsframe** [comment]
Duplicate of #51

**Comment by bwhiteman** [comment]
The Atlantic is another example
<img width="1440" alt="screen shot 2016-01-13 at 8 02 20 am" src="https://cloud.githubusercontent.com/assets/1516655/12294981/2715f3a8-b9cc-11e5-8d20-8bdb934f9d68.png">

**Comment by bwhiteman** [comment]
Details of 51 which is being closed:

The info panel does not open on some sits. Examples include: reuters.com, wsj.com

**Comment by michaelsframe** [comment]
This should be OBE with #161. Confirm?

**Comment by bmcdougald** [comment]
indeed, no longer an issue with the new panel.
