### ISSUE TITLE
Recursive Delete is broken for Trails and Domains

### ISSUE THREAD

**Issue by michaelsframe** [Sotera/DatawakeDepot#59]
Deleting a domain should also delete its domain entity types and domain items.

Deleting a trail should also delete trail urls and trail url extractions.

This is probably most easily accomplished by modifying the existing recursive delete in the service, however, the best design moving forward is to modify the model.js file for dw-domain and dw-trail to have an on-delete action. There is an existing loopback ticket regarding this issue (https://github.com/strongloop/loopback-datasource-juggler/issues/88#issuecomment-167369880)

**Comment by bwhiteman** [comment]
I'm making this as a pretty low priority as I don't see a lot of need for deleting trails and domains from a user perspective.

**Comment by michaelsframe** [comment]
merged to develop e3228fe7960352cee5c3fff790be43c39f38a8f8
