### ISSUE TITLE
Add new values to the User

### ISSUE THREAD

**Issue by bwhiteman** [Sotera/DatawakeDepot#6]
Need to update the user account whenever a new or change is made for that user involving Teams, Domains, or Trails. Currently the user has to log out and back in again to see the change reflected.

**Comment by michaelsframe** [comment]
You're talking about the AppAuthUser that gets used to populate dropdowns everywhere right?

**Comment by bwhiteman** [comment]
It seems like if I change the team in the plugin, the trails list will be updated, we need to handle this better and either add it to the list when the trail is created or refresh the list before displaying it.

**Comment by michaelsframe** [comment]
Ok, so specifically we need changes in the depot for user to send events to the addin which will cause a refresh on the toolbar.

**Comment by bwhiteman** [comment]
Closed as obe by several other tickets.
