### ISSUE TITLE
TrailUrl Search terms should be persisted 

### ISSUE THREAD

**Issue by michaelsframe** [Sotera/DatawakeDepot#62]
Forensic currently calculates the searchTerms for a url each time it runs.  Instead we need to determine and persist the search terms when the url is added during trailing.  

I've added a searchTerms property to the dw-trail-url.json model but nothing currently populates it.

**Comment by michaelsframe** [comment]
Completed and submitted pull request #102

**Comment by bmcdougald** [comment]
Tested.  Looks good with the exception of Google and Wikipedia
