### ISSUE TITLE
Larger content pages may break extraction

### ISSUE THREAD

**Issue by bmcdougald** [Sotera/DatawakeDepot#66]
Seems that if there's a lot to extract on a page, the extractor just gives up.  Small pages seem to be extracting ok.

**Comment by michaelsframe** [comment]
This was a bug in the stanford NER (node-ner), stdout maxBuffer exceeded.

I forked the node-ner project to Sotera/node-ner, made the fix to increase the buffer size, and committed the change.  I then modified the StanNER extractor to utilize the fork I created.  

https://github.com/Sotera/DatawakeSampleExtractor/commit/f20acf8095bc84836d72a23928a71f858957b53b
