### ISSUE TITLE
Selecting Trail Extractions crashes node server

### ISSUE THREAD

**Issue by bmcdougald** [Sotera/DatawakeDepot#68]
On branch 32-extractor-source-from-develop after trailing and getting extractions, if I click on Trail Extractions link in the sidebar node server crashes with the following error every time:

/home/ubuntu/src/DatawakeDepot/node_modules/loopback/node_modules/express/lib/response.js:242
  var body = JSON.stringify(val, replacer, spaces);
                  ^
RangeError: Invalid string length
    at join (native)
    at Object.stringify (native)
    at ServerResponse.json (/home/ubuntu/src/DatawakeDepot/node_modules/loopback/node_modules/express/lib/response.js:242:19)
    at Object.sendBodyJson [as sendBody](/home/ubuntu/src/DatawakeDepot/node_modules/loopback/node_modules/strong-remoting/lib/http-context.js:497:7)
    at HttpContext.done (/home/ubuntu/src/DatawakeDepot/node_modules/loopback/node_modules/strong-remoting/lib/http-context.js:632:22)
    at /home/ubuntu/src/DatawakeDepot/node_modules/loopback/node_modules/strong-remoting/lib/rest-adapter.js:459:11
    at /home/ubuntu/src/DatawakeDepot/node_modules/loopback/node_modules/async/lib/async.js:251:17
    at /home/ubuntu/src/DatawakeDepot/node_modules/loopback/node_modules/async/lib/async.js:154:25
    at /home/ubuntu/src/DatawakeDepot/node_modules/loopback/node_modules/async/lib/async.js:248:21
    at /home/ubuntu/src/DatawakeDepot/node_modules/loopback/node_modules/async/lib/async.js:612:34

**Comment by bwhiteman** [comment]
Due to the long wait on the pull request, it will probably be easier to redo this fix rather than trying to find the error because there is a lot of new code and conflicts.

**Comment by michaelsframe** [comment]
Trail Extractions is no longer available on the menu.  The only way it can be accessed now is via the TrailUrls page (itself acessed via Trails page only).

This change limits Trail Extractions to only the extractions relevant to the specific Trail/TrailUrl and should prevent the described bug.

**Comment by bwhiteman** [comment]
Confirmed
