### ISSUE TITLE
Deleting an extractor from depot list hangs depot page

### ISSUE THREAD

**Issue by bmcdougald** [Sotera/DatawakeDepot#69]
This is an odd bug, but easy to repro.  Branch being tested is 32-extractor-source-from-develop (but that may not be important to this issue specifically).

Behavior is if you have multiple extractors in the extractors management page of the depot and click on the icon to delete one of the extractors, you get the confirmation message to which you select yes to delete.  The list goes blank as if it deleted all the other extractors too, and the loading bar at the top of the page starts scrolling.  It gets almost to the end and just hangs there.  The only way to resolve this is to logout and then back in again.  When you do, you'll see that the one you deleted is gone and the others did not get deleted inadvertently.

**Comment by bwhiteman** [comment]
@bmcdougald can you reproduce this? I have not been able to.

**Comment by michaelsframe** [comment]
Once an extractor is added to a domain it gets put in a list in the ExtractorService to be polled for results.  Forever (whenever DW is started this list of domain extractors is retrieved and polling begins).

When an Extractor is removed we need to 1) stop the polling service  2) remove the extractor record  3)requery to get the list of updated domain extractors and to start again.

**Comment by bwhiteman** [comment]
For the time being, I don't see much need for doing this for SUG/Pilots.

**Comment by bmcdougald** [comment]
This is no longer hanging on delete.  closing as no longer an issue / fixed indirectly
