### ISSUE TITLE
Forensic page Entities & Visited Links tabs have table issues

### ISSUE THREAD

**Issue by bmcdougald** [Sotera/DatawakeDepot#70]
Two issues are immediately apparent on both of these tabs.  First, if one of the columns (e.g. URL) is long, for example having multiple URLs listed, it makes the column very large.  This pushes subsequent columns to the right.  It easily can create a situation where the table width is then wider than your screen.  This would be only a minor annoyance if there was horizontal scroll capability, but there isn't, so anything pushed beyond your window view cannot be seen.  You cannot drag/resize the column widths either to attempt to resolve this.

Second issue with the tables are that even though they appear to have sorting capability at each column heading...it does not appear to work.

**Comment by bmcdougald** [comment]
Some of the sorting has been fixed in these tables in subsequent checkins by brandon, however the URL column in the Entities table still does not sort.

**Comment by michaelsframe** [comment]
I had to similarly deal with the url wrapping issue in the TrailUrls list view and got by it by just adding the bootstrap classes to the TD.  This makes it wrap naturally and keeps the URL intact:

```
      td.col-sm-3.col-md-3.col-lg-3
        a(href='', ui-sref='app.dwTrailUrls.view({id: trailUrl.id, trailId:currentTrailId})') {{trailUrl.url}}
```

**Comment by bwhiteman** [comment]
@bmcdougald This should be ready for retest.

**Comment by bmcdougald** [comment]
Sorting of URL column in Entities tab still does not work.
