### ISSUE TITLE
column sizing in toolbar causes bad wrapping of toggle widgets

### ISSUE THREAD

**Issue by bmcdougald** [Sotera/DatawakeDepot#72]
Resizing the browser window forces a wrapping of the Show Domain Items / Show Panel column.  When it does this, the toggle for Show Panel gets thrown down and below Show Domain Items and is cut off.  Maybe we can set a minimum width on reactive sizing for this particular column to avoid this.  See screenshot.
![screen shot 2016-01-06 at 11 49 44 am](https://cloud.githubusercontent.com/assets/10615545/12149882/db7e126e-b46b-11e5-9e4b-f2622e01348d.png)

**Comment by bwhiteman** [comment]
Closed in pull 119
