### ISSUE TITLE
Domain Items Highlight toggle may need refresh to function

### ISSUE THREAD

**Issue by bmcdougald** [Sotera/DatawakeDepot#73]
If you start trailing and have the toggle to highlight domain items on, it may not highlight them if the page loads after this is toggled.  You man need to toggle it off, then back on again to get them to highlight.  Think this is an order of operation sort of problem perhaps.

**Comment by michaelsframe** [comment]
Completed and submitted pull request #104

**Comment by bmcdougald** [comment]
Tested, looks good.  Tracking related issue with #114
