### ISSUE TITLE
Domains: restrict by user Teams

### ISSUE THREAD

**Issue by michaelsframe** [Sotera/DatawakeDepot#80]
A user should only see the Domains for teams that they belong to, not all domains as is currently displayed.

**Comment by bwhiteman** [comment]
I'm not assigning this to 2.1 as we can give pilot users their own instance to work around this issue.

**Comment by michaelsframe** [comment]
Let's discuss, it was fairly straightforward to implement (work is done already for Teams and can easily be done for Domains).  It would make managing instances easier if we only have one to support.

**Comment by michaelsframe** [comment]
Done

**Comment by michaelsframe** [comment]
pushed additional fix

**Comment by michaelsframe** [comment]
Is this still occurring?

**Comment by bmcdougald** [comment]
Looks good, tested on develop branch.
