### ISSUE TITLE
Creating a user from the toolbar requires training

### ISSUE THREAD

**Issue by bwhiteman** [Sotera/DatawakeDepot#83]
We need to give some cue to the user on how to create a new trail. The only way I knew the functionality was there was to go to the issue in github and read the comments. There either needs to be an item to select in the drop-down or some sort of hint to the user.

**Comment by michaelsframe** [comment]
Adding an item to the list is problematic, but we can add a subdued text to the inputbox that appears that says something like "Create new trail or click to select existing"

**Comment by bwhiteman** [comment]
Duplicate of 74.
