### ISSUE TITLE
Info panel covers page content

### ISSUE THREAD

**Issue by bwhiteman** [Sotera/DatawakeDepot#84]
The information panel covers page content giving the user no way to see the page.

<img width="1437" alt="screen shot 2016-01-07 at 12 06 42 pm" src="https://cloud.githubusercontent.com/assets/1516655/12176827/4f608146-b537-11e5-927e-455d2ffaf528.png">
<img width="1437" alt="screen shot 2016-01-07 at 12 06 56 pm" src="https://cloud.githubusercontent.com/assets/1516655/12176826/4f5e0b00-b537-11e5-8064-3c776d3af2f2.png">

**Comment by michaelsframe** [comment]
There is a workaround, the user can toggle the panel on and off from the toolbar to see content under the panel.  

We had considered making it floating, but with the proposed move to the new Firefox #65 I figure the dev effort is best spent there.

**Comment by bwhiteman** [comment]
Not including this in 2.1. We will need to mention this as a known issue for the SUG and train users to toggle the panel while we refactor.

**Comment by michaelsframe** [comment]
being resolved with #65. Will not fix here.
