### ISSUE TITLE
Domain Entity Types should be shareable across multiple domains

### ISSUE THREAD

**Issue by bwhiteman** [Sotera/DatawakeDepot#9]
(Mike and I talked about this one…realize it’s future implementation goal)

Entity Types should be shareable across multiple domains.  For instance a type of ‘email’ or ‘address’ might be valid in several domains.

**Comment by michaelsframe** [comment]
I believe that we are moving away from the idea of a defined set of entity types per domain.  Instead, a domain's entity types will be defined by the extractors that the domain uses.  In this way we don't have to map extractor types to domain entity types.

**Comment by michaelsframe** [comment]
Per our discussion yesterday, it sounds like we won't have "stock" entity types and will instead allow the user to add those from Entity Extractions.  Can we close this issue?

**Comment by bwhiteman** [comment]
I'm closing this ticket as OBE.
