### ISSUE TITLE
Depot: Deleting a trail during creation hangs delete operation

### ISSUE THREAD

**Issue by bmcdougald** [Sotera/DatawakeDepot#93]
Kinda a minor bug.  If a user goes to create a new trail, has the template page up, then clicks on the "delete" button...they get the confirmation "Are you sure you want to delete", but if you say OK to delete it, nothing happens and the dialog confirmation stays active.  Maybe we should disable the delete button until working with an actually persisted trail...or at least remove the delete button from the template screen perhaps.

**Comment by bmcdougald** [comment]
This is actually happening for a lot of the deletes.  Saw it on Trails and Teams too.

**Comment by michaelsframe** [comment]
fixed for Teams, Trails, Trail Urls, Domains, Domain Items, Users, CrawlType, ServiceType, Extractor.

Since we are cancelling the create, there is no actual Delete to perform, hence the object does not exist.  Added test to see if the object exists before trying to delete it.

**Comment by michaelsframe** [comment]
merged https://github.com/Sotera/DatawakeDepot/commit/c25217271190e82514e8c67190c83b84e50cac22

**Comment by bmcdougald** [comment]
tested and closing as fixed
