### ISSUE TITLE
Depot: Creating new trail gives duplicate picklist items

### ISSUE THREAD

**Issue by bmcdougald** [Sotera/DatawakeDepot#94]
Think this may have been introduced as part of the work to limit trails to specific teams.  If you click on the teams pulldown, you'll start seeing duplicate choices in the list after you have a trail assigned to a second team only.

**Comment by michaelsframe** [comment]
fixed https://github.com/Sotera/DatawakeDepot/commit/7582027d89dd470da4cf259cb84b64324f782be9

**Comment by bmcdougald** [comment]
Seems to be fixed.
