### ISSUE TITLE
Depot: Edit Trail has uneditable empty domains section

### ISSUE THREAD

**Issue by bmcdougald** [Sotera/DatawakeDepot#95]
The table shows the trail is associated with a domain, however if you edit the trail, the edit screen has a grayed out picklist for domain with nothing selected.
![screen shot 2016-01-11 at 11 22 29 am](https://cloud.githubusercontent.com/assets/10615545/12240868/77e47ed0-b855-11e5-93f9-8d42ae48070b.png)

**Comment by michaelsframe** [comment]
fixed with #141 https://github.com/Sotera/DatawakeDepot/commit/d06548c2f4436a9d55eb96b113c5668980e2d829
