### ISSUE TITLE
Depot: edit domain items yields 404 error and blank template page

### ISSUE THREAD

**Issue by bmcdougald** [Sotera/DatawakeDepot#99]
Click on the edit pencil for a Domain Item in the depot and you get a 404 popup and whited-out template page for edit/create

**Comment by michaelsframe** [comment]
Is this still occurring?

**Comment by bmcdougald** [comment]
@michaelsframe yes it is.

**Comment by bmcdougald** [comment]
OK, no it isn't.  Looks like it's fixed.  My server repo was holding onto something and didn't reflect the change.  Wiping the repo, recloning solved the discrepancy
